const express = require("express");
const router = express.Router();
const { sendMail } = require("../utils/mailer");
const nodemailer = require("nodemailer");
const Order = require("../models/Order");
const Product = require("../models/product");

// Dev-only: send a test email and return Ethereal preview URL when available
router.get("/send-test-email", async (req, res) => {
  try {
    if (process.env.NODE_ENV === "production") {
      return res.status(403).json({ message: "Forbidden in production" });
    }

    const to = req.query.to || process.env.ADMIN_NOTIFICATION_EMAIL || "test@example.com";
    const subject = req.query.subject || `Kokoru Test Email - ${new Date().toISOString()}`;
    const html = `
      <div style="font-family:Arial, Helvetica, sans-serif">
        <h3>Kokoru Test Email</h3>
        <p>This is a test message generated by /api/dev/send-test-email.</p>
        <p>Time: ${new Date().toLocaleString()}</p>
      </div>
    `;

    const info = await sendMail({ to, subject, html });

    // If using Ethereal, nodemailer.getTestMessageUrl(info) will return a preview URL
    const preview = nodemailer.getTestMessageUrl(info) || null;

    res.json({ success: true, to, info: { messageId: info && info.messageId }, preview });
  } catch (err) {
    console.error("❌ send-test-email failed:", err && err.message ? err.message : err);
    res.status(500).json({ success: false, message: err.message || String(err) });
  }
});

// Dev-only: create a test order (bypasses payment) so we can validate admin listing & emails
router.post("/create-test-order", async (req, res) => {
  try {
    if (process.env.NODE_ENV === "production") return res.status(403).json({ message: "Forbidden in production" });

    const { cart = [], address = {}, userEmail = null, customerName = null, contact = null, coupon = null, discountAmount = 0, totalAfterDiscount = null } = req.body;

    // Minimal safety: ensure cart has at least one item
    if (!Array.isArray(cart) || cart.length === 0) return res.status(400).json({ message: "Cart required" });

    const items = cart.map((it) => ({
      productId: it._id,
      name: it.name || it.productName || 'Unknown',
      price: it.ourPrice || it.price || 0,
      quantity: it.quantity || 1,
      colorName: it.colorName || null,
      sizeLabel: it.sizeLabel || null,
    }));

    const amount = items.reduce((s, i) => s + (i.price || 0) * (i.quantity || 1), 0);

    const newOrder = new Order({
      userEmail,
      customerName: customerName || (address && (address.name || address.label)) || userEmail || 'DevUser',
      contact,
      address,
      items,
      amount,
      paymentId: 'dev-test',
      status: 'paid',
      coupon: coupon || null,
      discountAmount: discountAmount || 0,
      totalAfterDiscount: typeof totalAfterDiscount !== 'undefined' && totalAfterDiscount !== null ? totalAfterDiscount : (amount - (discountAmount || 0)),
    });

    const saved = await newOrder.save();

    // Notify admin (best-effort)
    try {
      const adminEmail = process.env.ADMIN_NOTIFICATION_EMAIL || 'test@example.com';
      if (adminEmail) {
        await sendMail({
          to: adminEmail,
          subject: `Dev: New Order ${saved._id}`,
          html: `<p>Dev test order created: <strong>${saved._id}</strong></p><p>Amount: ₹${saved.amount}</p>`,
        });
      }
    } catch (e) {
      console.error('Dev: admin notify failed', e);
    }

    // Try to send customer email if provided
    try {
      if (userEmail) {
        await sendMail({ to: userEmail, subject: `Your Dev Order ${saved._id}`, html: `<p>This is a dev-order confirmation for ${saved._id}</p>` });
      }
    } catch (e) {
      console.error('Dev: customer notify failed', e);
    }

    res.json({ success: true, order: saved });
  } catch (err) {
    console.error('Dev create-test-order failed', err);
    res.status(500).json({ success: false, message: err.message || String(err) });
  }
});

module.exports = router;

